name: CI

on: [push]

jobs:
  build:

    runs-on: bp-ubuntu-latest-x64-2x

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit ./tests --log-junit junit.xml

    - name: Upload test results to BuildPulse

      # BuildPulse is most useful when tests FAILED, so run on red builds too.

      if: always()

      uses: BuildPulseLLC/test-reporter-action@v3

      with:

        api-token: ${{ secrets.BUILDPULSE_API_TOKEN }}

        path: .
